// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { CRAZZY_SUPABASE_PUBLIC } from '@/config/supabasePublic';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || CRAZZY_SUPABASE_PUBLIC.url;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || CRAZZY_SUPABASE_PUBLIC.publishableKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});